# Generated by Django 5.2.17 on 2026-08-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="keycloak_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
