[project]
name = "pyobs-archive"
version = "2.0.0.dev7"
description = "A webservice for an archive for astronomical images."
requires-python = ">=3.11"
dependencies = [
    "astropy>=6.1",
    "Django>=5.2,<6",
    "django-oauth-toolkit>=3.4.0,<4",
    "djangorestframework>=3.18.0",
    "gunicorn>=23.0.0",
    "matplotlib>=3.9",
    "numpy>=2.0",
    "psycopg2-binary>=2.9",
    "zipstream>=1.1.4",
    "django-crispy-forms>=2.3",
    "django-cors-headers>=4.4",
    "cryptography>=43.0",
    "whitenoise>=6.7",
    "pyobs-auth>=2.0.0.dev7",
]

[tool.uv]
package = false
