# Generated by Django 2.2.4 on 2019-09-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='filename',
            new_name='basename',
        ),
    ]
