# Generated by Django 2.2.4 on 2019-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190916_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='related',
            field=models.ManyToManyField(to='api.Frame'),
        ),
    ]
