# Generated by Django 2.2.4 on 2019-10-02 09:23
import os
from astropy.io import fits
from django.db import migrations, models

from pyobs_archive import settings


def set_night(apps, schema_editor):
    # get Frame class
    Frame = apps.get_model('api', 'Frame')

    # get archive root
    root = settings.ARCHIV_SETTINGS['ARCHIVE_ROOT']

    # loop all frames
    for frame in Frame.objects.all():
        # get path to file
        path = os.path.join(root, frame.path, frame.basename + '.fits.fz')

        try:
            # get header
            hdr = fits.getheader(path, 'SCI')

            # set night and save
            frame.night = hdr['DAY-OBS']
            frame.save()

        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190917_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='night',
            field=models.DateField(db_index=True, default='1970-01-01', verbose_name='Night of observation'),
            preserve_default=False,
        ),
        migrations.RunPython(set_night),
    ]
