# Generated by Django 2.2.4 on 2019-12-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_frame_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='REQNUM',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Unique number for request'),
        ),
    ]
