# Generated by Django 5.2.17 on 2026-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_frame_obsnum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="basename",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Name of file"
            ),
        ),
    ]
