# Generated by Django 5.2.17 on 2026-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_frame_basename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="DATAMEAN",
            field=models.FloatField(
                default=None, null=True, verbose_name="Mean data value"
            ),
        ),
    ]
