# Generated by Django 5.2.17 on 2026-08-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_frame_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="frame",
            name="PROJECT",
            field=models.CharField(
                db_index=True,
                default=None,
                max_length=10,
                null=True,
                verbose_name="Project code",
            ),
        ),
    ]
