# Generated by Django 5.2.17 on 2026-08-24 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0012_frame_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Project code",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Project name")),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        verbose_name="Visible to every authenticated user",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
