# Generated by Django 2.2.4 on 2019-08-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Telescope')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, verbose_name='Name of file')),
                ('image_type', models.CharField(max_length=10, verbose_name='Type of image')),
                ('reduction_level', models.IntegerField(default=0, verbose_name='Reduction level')),
                ('date_obs', models.DateTimeField(verbose_name='Time exposure started')),
                ('target', models.CharField(max_length=50, verbose_name='Name of target')),
                ('vec_x', models.FloatField(verbose_name='Telescope RA/Dec position as vector, X component')),
                ('vec_y', models.FloatField(verbose_name='Telescope RA/Dec position as vector, Y component')),
                ('vec_z', models.FloatField(verbose_name='Telescope RA/Dec position as vector, Z component')),
                ('tel_ra', models.FloatField(null=True, verbose_name='Telescope Right Ascension')),
                ('tel_dec', models.FloatField(null=True, verbose_name='Telescope Declination')),
                ('tel_alt', models.FloatField(verbose_name='Altitude of telescope at start of exposure')),
                ('tel_az', models.FloatField(verbose_name='Azimuth of telescope at start of exposure')),
                ('tel_focus', models.FloatField(verbose_name='Focus of telescope')),
                ('sol_alt', models.FloatField(verbose_name='Elevation of sun above horizon in deg')),
                ('moon_alt', models.FloatField(verbose_name='Elevation of moon above horizon in deg')),
                ('moon_ill', models.FloatField(verbose_name='Illuminated fraction of moon surface')),
                ('moon_sep', models.FloatField(verbose_name='Ok-sky distance of object to Moon in deg')),
                ('exp_time', models.FloatField(verbose_name='Exposure time')),
                ('filter', models.CharField(max_length=20, verbose_name='Filter used')),
                ('binning', models.IntegerField(default=1, verbose_name='Binning of image')),
                ('offset_x', models.IntegerField(default=0, verbose_name='X offset of image in unbinned pixels')),
                ('offset_y', models.IntegerField(default=0, verbose_name='Y offset of image in unbinned pixels')),
                ('width', models.IntegerField(verbose_name='Width of image in binned pixels')),
                ('height', models.IntegerField(verbose_name='Height of image in binned pixels')),
                ('data_mean', models.FloatField(verbose_name='Mean data value')),
                ('quality', models.FloatField(verbose_name='Estimation of image quality (0..1)')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Instrument')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Telescope')),
            ],
        ),
    ]
