"""
Django settings for pyobs_archive project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import logging
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from rest_framework.authentication import TokenAuthentication

_settings_log = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The old value that used to live here was committed to a public repo and must never be used
# again. Set SECRET_KEY in the environment for any real deployment; this fallback is for local
# development only.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-dev-only-3f1a9c7e2b6d4f80a1c5e9b3d7f2a6c8e0b4d9f1a3c5e7b9d1f3a5c7e9b1d3f5'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'false').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# The bundled nginx.conf.example sets "X-Forwarded-Proto: $scheme" and is the only public
# entry point (gunicorn itself is not published), so it's safe to trust this header to tell
# Django the original request was HTTPS. Without this, request.build_absolute_uri() would
# always use "http://", causing mixed-content issues behind a TLS-terminating proxy.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'oauth2_provider',
    'pyobs_auth',
    'pyobs_archive.api',
    'pyobs_archive.authentication',
    'pyobs_archive.frontend'
]

# Local Django username/password is the default login for every pyobs web project; Keycloak is
# an optional addon on top, not a replacement - see pyobs_auth.views for the separate,
# view-based Keycloak login flow (an OIDC redirect doesn't fit the AUTHENTICATION_BACKENDS shape).
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware'
]

ROOT_URLCONF = 'pyobs_archive.urls'

# Distinct from other pyobs Django apps (e.g. portal, web-admin) so browser
# cookies don't collide when run on localhost at once - cookies are scoped by host, not port.
SESSION_COOKIE_NAME = 'archive_sessionid'
CSRF_COOKIE_NAME = 'archive_csrftoken'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pyobs_archive.context_processors.keycloak',
            ],
        },
    },
]

WSGI_APPLICATION = 'pyobs_archive.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('SQL_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('SQL_DATABASE', os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': os.environ.get('SQL_USER', 'user'),
        'PASSWORD': os.environ.get('SQL_PASSWORD', 'password'),
        'HOST': os.environ.get('SQL_HOST', 'localhost'),
        'PORT': os.environ.get('SQL_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', '/static/')

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# allow access from other pages, e.g. portal
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]

# logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(filename)s:%(lineno)d %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'pyobs_auth.authentication.KeycloakAuthentication',  # optional: Bearer tokens from Keycloak
    ),
}

# Keycloak is optional: leaving SERVER_URL unset means pyobs_auth.settings.get_settings() raises
# on first use, which only matters if something actually presents a Keycloak Bearer token or
# hits the /accounts/keycloak/ login views - local Django username/password keeps working
# regardless.
PYOBS_AUTH = {
    'SERVER_URL': os.getenv('KEYCLOAK_SERVER_URL', ''),
    'REALM': os.getenv('KEYCLOAK_REALM', 'pyobs'),
    'CLIENT_ID': os.getenv('KEYCLOAK_CLIENT_ID', 'archive'),
    'CLIENT_SECRET': os.getenv('KEYCLOAK_CLIENT_SECRET', ''),
    'REDIRECT_URI': os.getenv('KEYCLOAK_REDIRECT_URI', ''),
    'POST_LOGOUT_REDIRECT_URI': os.getenv('KEYCLOAK_POST_LOGOUT_REDIRECT_URI', ''),
    # Optional one-click IdP login: IDP_HINT is passed to Keycloak as kc_idp_hint (skips its
    # login/IdP-selection page, going straight to that identity provider, e.g. GWDG SSO);
    # IDP_LABEL is the button label on the login page. Both are deployment-specific.
    'IDP_HINT': os.getenv('KEYCLOAK_IDP_HINT', ''),
    'IDP_LABEL': os.getenv('KEYCLOAK_IDP_LABEL', ''),
    'USER_RESOLVER': 'pyobs_archive.authentication.keycloak.resolve_user',
}

# Settings-configured admin account (optional): synced to a real superuser after every
# `manage.py migrate` (see pyobs_archive.authentication.admin_sync, wired up in
# AuthenticationConfig.ready() via the post_migrate signal) instead of needing an interactive
# `createsuperuser` step on a fresh deployment. Leave ADMIN_USERNAME unset to disable.
# Generate the hash: uv run python -c \
#   "from django.contrib.auth.hashers import make_password; print(make_password('yourpassword'))"
ADMIN_USERNAME = os.getenv('ADMIN_USERNAME', '')
ADMIN_PASSWORD_HASH = os.getenv('ADMIN_PASSWORD_HASH', '')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# App settings
LOGO_LINK = 'https://pyobs.github.io'
ARCHIVE_ROOT = os.environ.get('ARCHIVE_ROOT', '/data/')
PATH_FORMATTER = os.environ.get('PATH_FORMATTER', '{SITEID}/{DAY-OBS}/')
FILENAME_FORMATTER = os.environ.get('FILENAME_FORMATTER') or None

# max upload size in bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = 50*1024*1024

# pyobs-portal connection, used to mirror projects/users (`manage.py sync_projects`)
# and to resolve REQNUM -> project at ingest time - see
# specs/plans/2026-08-20-archive-project-access-control.md. Leaving PROJECT_ACCESS_CONTROL unset
# (or falsy) keeps today's behavior (no per-project access filtering); it's independent of
# whether the portal connection itself is configured.
# PORTAL_URL/PORTAL_TOKEN/PORTAL_TIMEOUT renamed from ROBOTIC_BACKEND_URL/_TOKEN/_TIMEOUT
# (pyobs-robotic-backend -> pyobs-portal rename); the old names are still read as a fallback
# for one release so existing deployments don't silently break.
PORTAL_URL = os.environ.get('PORTAL_URL') or os.environ.get('ROBOTIC_BACKEND_URL', '')
PORTAL_TOKEN = os.environ.get('PORTAL_TOKEN') or os.environ.get('ROBOTIC_BACKEND_TOKEN', '')
_PORTAL_TIMEOUT_DEFAULT = 5.0
_portal_timeout_raw = os.environ.get('PORTAL_TIMEOUT') or os.environ.get('ROBOTIC_BACKEND_TIMEOUT', _PORTAL_TIMEOUT_DEFAULT)
try:
    PORTAL_TIMEOUT = float(_portal_timeout_raw)
except ValueError:
    _settings_log.warning(
        "Invalid PORTAL_TIMEOUT=%r, falling back to %s seconds.",
        _portal_timeout_raw, _PORTAL_TIMEOUT_DEFAULT
    )
    PORTAL_TIMEOUT = _PORTAL_TIMEOUT_DEFAULT
PROJECT_ACCESS_CONTROL = os.environ.get('PROJECT_ACCESS_CONTROL', 'false').lower() in ('1', 'true', 'yes')

# try to import a local_settings.py
try:
    from .local_settings import *
except ImportError:
    pass
