# Generated by Django 2.2.4 on 2019-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=50, verbose_name='Name of file')),
                ('path', models.CharField(max_length=100, verbose_name='Path to file')),
                ('SITEID', models.CharField(db_index=True, max_length=5, verbose_name='Site of observation')),
                ('TELID', models.CharField(db_index=True, max_length=5, verbose_name='Telescope used for observation')),
                ('INSTRUME', models.CharField(db_index=True, max_length=5, verbose_name='Instrument used for observation')),
                ('IMAGETYP', models.CharField(db_index=True, max_length=10, verbose_name='Type of image')),
                ('RLEVEL', models.IntegerField(db_index=True, default=0, verbose_name='Reduction level')),
                ('DATE_OBS', models.DateTimeField(db_index=True, verbose_name='Time exposure started')),
                ('OBJECT', models.CharField(db_index=True, default=None, max_length=50, null=True, verbose_name='Name of Object')),
                ('TEL_RA', models.FloatField(null=True, verbose_name='Telescope Right Ascension')),
                ('TEL_DEC', models.FloatField(null=True, verbose_name='Telescope Declination')),
                ('vec_x', models.FloatField(db_index=True, null=True, verbose_name='Telescope orientation as vector, x component')),
                ('vec_y', models.FloatField(db_index=True, null=True, verbose_name='Telescope orientation as vector, y component')),
                ('vec_z', models.FloatField(db_index=True, null=True, verbose_name='Telescope orientation as vector, z component')),
                ('TEL_ALT', models.FloatField(default=None, null=True, verbose_name='Altitude of telescope at start of exposure')),
                ('TEL_AZ', models.FloatField(default=None, null=True, verbose_name='Azimuth of telescope at start of exposure')),
                ('TEL_FOCU', models.FloatField(default=None, null=True, verbose_name='Focus of telescope')),
                ('SUNALT', models.FloatField(default=None, null=True, verbose_name='Elevation of sun above horizon in deg')),
                ('SUNDIST', models.FloatField(default=None, null=True, verbose_name='Ok-sky distance of object to Sun in deg')),
                ('MOONALT', models.FloatField(default=None, null=True, verbose_name='Elevation of moon above horizon in deg')),
                ('MOONFRAC', models.FloatField(default=None, null=True, verbose_name='Illuminated fraction of moon surface')),
                ('MOONDIST', models.FloatField(default=None, null=True, verbose_name='Ok-sky distance of object to Moon in deg')),
                ('EXPTIME', models.FloatField(db_index=True, verbose_name='Exposure time')),
                ('FILTER', models.CharField(db_index=True, default=None, max_length=20, null=True, verbose_name='Filter used')),
                ('XBINNING', models.IntegerField(default=1, verbose_name='Binning of image in X direction')),
                ('YBINNING', models.IntegerField(default=1, verbose_name='Binning of image in Y direction')),
                ('XORGSUBF', models.IntegerField(default=0, verbose_name='X offset of image in unbinned pixels')),
                ('YORGSUBF', models.IntegerField(default=0, verbose_name='Y offset of image in unbinned pixels')),
                ('width', models.IntegerField(verbose_name='Width of image in binned pixels')),
                ('height', models.IntegerField(verbose_name='Height of image in binned pixels')),
                ('DATAMEAN', models.FloatField(default=True, null=True, verbose_name='Mean data value')),
                ('related', models.ManyToManyField(related_name='_frame_related_+', to='archive.Frame')),
            ],
        ),
    ]
